name: Build 🧱 and Deploy 🛳

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 💳
        uses: actions/checkout@v4.1.7

      - name: Setup node 💻
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '22.x'

      - name: Install npm dependencies 🔗
        run: |
          rm package-lock.json
          npm cache clear -f
          npm install

      - name: Build for pages 📖
        env:
          NEXT_PUBLIC_BASE_PATH: /grb2nc.js
          NEXT_PUBLIC_SVG_SCALE: 1000
        run: |
          npm run build
          touch out/.nojekyll
          mv out out-pages

      - name: Deploy to GitHub-Pages 📖
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: out-pages
